# Generated by Django 3.2 on 2021-05-24 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionmesa',
            name='mozo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.mozo'),
        ),
        migrations.AlterField(
            model_name='asignacionmesa',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.sector'),
        ),
    ]
